### DISCUSSION TITLE
CASA task cabs

### DISCUSSION THREAD

**Discussion by o-smirnov** [caracal-pipeline/stimela#106] [Show and tell]
For the benefit of @caracal-pipeline/stimelators who want to improve their Stimela-fu, I'm going to highlight some cab examples. Look out for a few more such examples.

Here's an example of using the new ``casa-task`` flavour to wrap a CASA task:

```yml
  flagman:
    command: flagmanager
    flavour: casa-task
    inputs:
      ms: 
        dtype: MS
        required: true
        nom_de_guerre: vis   # CASA uses 'vis', we call it 'ms'
      versionname:
        info: "flag version name"
      mode: 
        choices: [save, restore, list]
        required: true
```

Here's another example. This is a cab that's based on the ``flagdata`` task, but calls it with a specific set of parameters, and extracts an output value from the output:

```yml
  flagsummary:
    command: flagdata
    flavour: casa-task
    inputs:
      ms: 
        dtype: MS
        required: true
        nom_de_guerre: vis
      spw:
        dtype: str
        default: all
      mode:
        implicit: 'summary'
    outputs:
      percentage:
        dtype: float
    management:
      wranglers:
        'Total Flagged: .* Total Counts: .* \((?P<percentage>[\d.]+)%\)':
          - PARSE_OUTPUT:percentage:float
          - HIGHLIGHT:bold green
```

Things to note:

* ``mode`` is implicitly fixed here: it is no longer a user-definable parameter of the cab, but it is passed as a parameter to the underlying task.

* ``management.wranglers`` can be defined to do all sorts of funky stuff with the console output. In this case, we parse out a percentage value, but also cause the relevant line to be highlighted in green.

**Comment by o-smirnov** [comment]
As a further twist on this, note that we can do cab specialization. So if, for example, @Athanaseus or @Mulan-94 write us a complete ``casa-flagmanager`` cab definition where all of the task parameters are exposed, the above code could be changed to provide a specialization, which defines only the necessary extra bits (such as making a parameter implicit):

```yml
  flagsummary:
    _use: cabs.casa-flagmanager
    inputs:
      mode:
        implicit: 'summary'
    outputs:
      percentage:
        dtype: float
    management:
      wranglers:
        'Total Flagged: .* Total Counts: .* \((?P<percentage>[\d.]+)%\)':
          - PARSE_OUTPUT:percentage:float
          - HIGHLIGHT:bold green
```
