### DISCUSSION TITLE
Generic file manipulation and shell cabs

### DISCUSSION THREAD

**Discussion by o-smirnov** [caracal-pipeline/stimela#24] [Ideas]
I find myself doing some generic file manipulation stuff in my pipeline. So first I defined a ``cp`` cab:

```yml
  cp:
    command: cp -a
    policies:
      positional: true
    inputs:
      src:
        dtype: File
        required: true
      dest:
        dtype: Union[File, Directory]
        required: true
        must_exist: false
```

Then I made an ``mv`` cab which only differs in the command. Then I thought why not unify them:

```yml
  fileops:
    command: '{current.command}'
    policies:
      positional: true
    inputs:
      command:
        choices: 
          - cp
          - mv
        policies:
          skip: true
      src:
        dtype: File
        required: true
      dest:
        dtype: Union[File, Directory]
        required: true
        must_exist: false
```

Then I realized I can have something even more generic:

```yml
  shell:
    command: '{current.command} {current.args}'
    policies:
      skip: true
    inputs:
      command:
        dtype: str
        required: true
      args:
        dtype: str
        required: true
```

The disadvantage of the latter is that there's no formal "file" output that could be linked in a subsequent step.

@SpheMakh thoughts on this? We should probably provide something along these lines among the standard cabs.
