### DISCUSSION TITLE
Making for-loops easiers

### DISCUSSION THREAD

**Discussion by o-smirnov** [caracal-pipeline/stimela#280] [Ideas]
@JSKenyon @Athanaseus I had a happy thought the other day. For-loops could be done somewhat simpler in the current stimela, thanks to the  endless flexibility of the YaML-merge behaviour.

I've previously suggested the Jove recipe pattern to you, where there is one "single observation" recipe, and a separate outer loop recipe which invokes the observation recipe as a sub-recipe.

It occurs to me this can be made less clumsy. Leave the single observation recipe as is (let's say it has an ``obs`` input determining which observation to use). Then make a separate ``loop-config.yml``

```yml
my-recipe:
  inputs:
    obs-list: 
      dtype: List[str]
      default: [foo, bar, etc.]
  for_loop:
    var: obs
    over: obs-list
```

Then things become as simple as 

```
$ stimela run recipe.yml obs=foo               # single observation
$ stimela run recipe.yml loop-config.yml       # loop
$ stimela run recipe.yml loop-config.yml obs-list="[not, a, default, list]"       
```

And for more elaborate things, define ``obs-config.yml`` with a ``my-recipe: assign_based_on: obs`` section which can tweak per-observation settings:

```
$ stimela run recipe.yml loop-config.yml obs-config.yml     # loop, with extra config
```

Thoughts?
