### ISSUE TITLE
add "profiles" section to config

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela#4]
I've settled on a standardized recipe which I want to apply in a few pre-defined ways, changing a few settings each time -- but in a synchronized way, i.e. with a different MS *and* a different output directory *and* a different pixel size, etc. It would be nice if I could "group" these settings into a single profile so I could activate them as a group.

This can be elegantly solved by allowing a ``--profile`` option and a freeform top-level ``profiles`` section e.g. like this:

```yml
profiles:
  uhf:
    # override with UHF-specific settings from oms-cabs
    lib:
      steps:
        wsclean:
          base:
            params:
              size: 12000
              scale: 1.6asec
              nchan: 6
  lband:
    lib:
      steps:
        wsclean:
          base:
            params:
              size: 10000
              scale: 0.8asec
              nchan: 8
  foo3:
    boom:
      inputs:
        dir_out: 
          default: 'obs3uhf'
        ms:
          default: ../msdir/1627405250_sdp_l0-J2009_2026-corr.ms  # UHF from 1st U+L obs
```

...so specifying ``--profile uhf,foo3`` in this case would pull take the contents of ``profiles.uhf`` and ``profiles.foo3``, and merge them on top of the loaded config.
