### ISSUE TITLE
Modularity: Using stimela to run multiple recipes causes errors with cult-cargo.

### ISSUE THREAD

**Issue by tmolteno** [caracal-pipeline/stimela#435]
Suppose I have two recipes. recipe-1 and recipe-2. I would like to use them from a higher level stimela recipe. Here's the high level one
```
# stimela run recipe-12.yml ms=~/astro/1519747221.subset.ms
_include:
    - recipe-1.yml
    - recipe-2.yml

recipe-1-2:
    inputs:
        ms:
            dtype: MS

    steps:
        stage-1:
            recipe: recipe-1
            params:
                ms: =recipe.ms
        stage-2:
            recipe: recipe-2
            params:
                ms: =recipe.ms
```
Recipe 1 and recipe 2 both use casa cabs. They both look like below. 
```
_include:
    - (cultcargo):
          - casa:
                - listobs.yml

recipe-1:
    inputs:
        ms:
            dtype: MS

    steps:
        listobs:
            cab: casa.listobs
            params:
                ms: =recipe.ms
```
so this is how to do it. This was a bug report, but the failure was an old version of cult-cargo installed (without listobs)
