### ISSUE TITLE
add python code cab

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela#5]
It would be useful to include small snippets of python as a cab definition.

**Comment by o-smirnov** [comment]
Example use case, see this current Ugly Kludge:

```yml
  print_uniq_column_values:
    command: "python3 -c 'from casacore.tables import table; import sys; print(len(set(table(sys.argv[1]).getcol(sys.argv[2]))),sys.argv[3]);'"
    policies:
      positional: true
    inputs:
      ms:
        dtype: MS
        required: true
      column:
        default: 'TIME'
      label:
        default: 'timeslots'
```

Figuring out how to nest quotes within quotes within quotes (for YML to parse into a shell command to parse into a python command) is a PITA, so rather have Python code.

**Comment by o-smirnov** [comment]
This was implemented by I forget which PR. Anyhow, it works. Here's an example python callable cab:

```yml
  extract_fits_timestamps:
    command: (image_utils)extract_fits_timestamps
    inputs:
      images:
        dtype: List[File]
        required: true
    outputs:
      outfile:
        dtype: File
```
